# Site settings
title: Garrett M. O'Day
email: goday@purdue.edu
url: https://gmoday.github.io
baseurl: /blog
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "I'm a Graduate Researcher, currently working on my Master's Thesis."
meta_author: O'Day Garrett

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 42b0e5 
  primary-rgb: "114,114,114" # i think it changes modal color during hover
  secondary: 727272 
  secondary-dark: 4d4d4d # outlines the menu and copyright footer

# Footer settings
footer:
  copyright: Garrett O'Day
  location: Purdue University
  social: Social Media
  credits: Jenkyll Theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: <a href="http://www.purdue.edu/hhs/psy/">Department of Psychological Sciences</a>
  - line: <a href="http://learninglab.psych.purdue.edu/">Cognition and Learning Lab</a>
# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
